### ISSUE TITLE
cluster: address last minute review items from PR 157

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#163]
https://github.com/mmatczuk/scylla-go-driver/pull/157

**Comment by Michal-Leszczynski** [comment]
```
        if r.Response == nil {
		r.Err = fmt.Errorf("response type not supported")
		return r
	}
```
I added this because of certain responses like Result or Event. For example, we get response with correct header describing some event. Event starts with a string describing the type of event, but if it is not supported (string is incorrect), we return nil from parse event. That's how we can still return nil from parse.

**Comment by Michal-Leszczynski** [comment]
What about log messages in **handleEvent** and its helper functions? In theory they are used inside conn loops, so should I give them **conn: ** prefix?

**Comment by mmatczuk** [comment]
The conn prefix is Conn::String output, I guess it should be cluster still.
